/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>

// External function for putchar (weak)
extern int __io_putchar(int ch) __attribute__((weak));
// External function for getchar (weak)
extern int __io_getchar(void) __attribute__((weak));

// Environment variables array
char *__env[1] = { 0 };
// Pointer to environment
char **environ = __env;

// Function to initialize monitor handles
void initialise_monitor_handles()
{
}

// Function to get process ID
int _getpid(void)
{
  return 1;
}

// Function to kill a process
int _kill(int pid, int sig)
{
  (void)pid;
  (void)sig;
  errno = EINVAL;
  return -1;
}

// Function to exit the program
void _exit (int status)
{
  _kill(status, -1);
  while (1) {}    /* Make sure we hang here */
}

// Function to read from file (weak)
__attribute__((weak)) int _read(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    *ptr++ = __io_getchar();
  }

  return len;
}

// Function to write to file (weak)
__attribute__((weak)) int _write(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    __io_putchar(*ptr++);
  }
  return len;
}

// Function to close file
int _close(int file)
{
  (void)file;
  return -1;
}

// Function to get file status
int _fstat(int file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

// Function to check if terminal
int _isatty(int file)
{
  (void)file;
  return 1;
}

// Function to seek in file
int _lseek(int file, int ptr, int dir)
{
  (void)file;
  (void)ptr;
  (void)dir;
  return 0;
}

// Function to open file
int _open(char *path, int flags, ...)
{
  (void)path;
  (void)flags;
  /* Pretend like we always fail */
  return -1;
}

// Function to wait for child process
int _wait(int *status)
{
  (void)status;
  errno = ECHILD;
  return -1;
}

// Function to unlink file
int _unlink(char *name)
{
  (void)name;
  errno = ENOENT;
  return -1;
}

// Function to get times
int _times(struct tms *buf)
{
  (void)buf;
  return -1;
}

// Function to get stat
int _stat(char *file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

// Function to link files
int _link(char *old, char *new)
{
  (void)old;
  (void)new;
  errno = EMLINK;
  return -1;
}

// Function to fork process
int _fork(void)
{
  errno = EAGAIN;
  return -1;
}

// Function to execute program
int _execve(char *name, char **argv, char **env)
{
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}